// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc4pH7DJvh12mXB0mpGo1QOsfg6kjkauQ',
    appId: '1:948052804089:web:8724d2a90583e81f203d28',
    messagingSenderId: '948052804089',
    projectId: 'flixtor-b43c5',
    authDomain: 'flixtor-b43c5.firebaseapp.com',
    storageBucket: 'flixtor-b43c5.appspot.com',
    measurementId: 'G-HP8KKG411Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD95XzSsyLndVKxgKF9yrTm--Z8r8gdu0',
    appId: '1:948052804089:android:959398510c76d7f8203d28',
    messagingSenderId: '948052804089',
    projectId: 'flixtor-b43c5',
    storageBucket: 'flixtor-b43c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfJ3pEYrMpRbxX58YILs9PK8yuf-zecd8',
    appId: '1:948052804089:ios:4e5a246678e7bdb2203d28',
    messagingSenderId: '948052804089',
    projectId: 'flixtor-b43c5',
    storageBucket: 'flixtor-b43c5.appspot.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfJ3pEYrMpRbxX58YILs9PK8yuf-zecd8',
    appId: '1:948052804089:ios:c447a962e6bef6ec203d28',
    messagingSenderId: '948052804089',
    projectId: 'flixtor-b43c5',
    storageBucket: 'flixtor-b43c5.appspot.com',
    iosBundleId: 'com.example.app1.RunnerTests',
  );
}
